app = "meme-competition"
primary_region = "syd"
kill_signal = "SIGINT"
kill_timeout = "5s"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[processes]
  # Django app process
  app = "daphne -p 8000 -b 0.0.0.0 MemeComp.asgi:application"

  # Celery worker process
  celery = "celery -A MemeComp worker -l info"

[env]
  PORT = "8000"

[[mounts]]
  source = "meme_comp_vol"
  destination = "/code/media"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app", "celery"]  # Include the Celery worker process in the services

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
