# fly.toml app configuration file generated for meme-competition on 2023-05-27T12:14:58+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "meme-competition"
primary_region = "syd"
kill_signal = "SIGINT"
kill_timeout = "5s"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[[mounts]]
  source = "meme_comp_vol"
  destination = "/code/media"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
