# Generated by Django 4.2.1 on 2023-05-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("app", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="current_meme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current",
                to="app.meme",
            ),
        ),
        migrations.CreateModel(
            name="SeenMeme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.competition",
                    ),
                ),
                (
                    "meme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.meme"
                    ),
                ),
            ],
            options={"unique_together": {("competition", "meme")}},
        ),
    ]
