# Generated by Django 4.2.1 on 2023-08-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_vote_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='tiebreaker',
            field=models.BooleanField(default=False),
        ),
    ]
