# Generated by Django 4.2.1 on 2023-08-08 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_competition_tiebreaker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="current_meme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current",
                to="app.meme",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="winning_meme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_competition",
                to="app.meme",
            ),
        ),
    ]
