# Generated by Django 4.2.1 on 2023-11-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0013_participant_ready")]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="timer_active",
            field=models.BooleanField(default=False),
        )
    ]
