# Generated by Django 4.2.1 on 2023-12-28 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_competition_round_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(choices=[('upload', 'uploaded a meme'), ('create', 'created the competition'), ('join', 'joined the competition'), ('start', 'started the competition'), ('cancel', 'cancelled the competition'), ('advance', 'advanced the competition'), ('vote', 'voted'), ('won', 'won the competition')], max_length=100)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
