# Generated by Django 4.2.1 on 2023-12-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0016_competitionlog")]

    operations = [
        migrations.RemoveField(model_name="competition", name="timer_active"),
        migrations.AddField(
            model_name="competition",
            name="timer_task_id",
            field=models.CharField(blank=True, max_length=765, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="competitionlog",
            name="event",
            field=models.CharField(
                choices=[
                    ("upload", "uploaded a meme"),
                    ("delete", "deleted a meme"),
                    ("create", "created the competition"),
                    ("join", "joined"),
                    ("start", "started the competition"),
                    ("cancel", "cancelled the competition"),
                    ("advance", "advanced the competition"),
                    ("settings", "updated the competition settings"),
                    ("vote", "voted"),
                    ("won", "won!"),
                ],
                max_length=100,
            ),
        ),
    ]
