# Generated by Django 4.2.1 on 2023-12-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0017_remove_competition_timer_active_and_more")]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="timer_timeout",
            field=models.PositiveIntegerField(blank=True, default=15),
        ),
        migrations.AddField(
            model_name="competition",
            name="with_timer",
            field=models.BooleanField(default=False),
        ),
    ]
