# Generated by Django 4.2.1 on 2023-12-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0018_competition_timer_timeout_competition_with_timer")]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="round_started_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        )
    ]
