# Generated by Django 4.2.1 on 2023-12-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0019_alter_competition_round_started_at")]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="timer_timeout",
            field=models.PositiveIntegerField(blank=True, default=15, null=True),
        )
    ]
