# Generated by Django 4.2.1 on 2024-01-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0021_remove_competition_finished_and_more")]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="timer_started_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        )
    ]
